version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: rails_svelte-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      #Change the below values to your own
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    #Below is the command to run the rails server in the background after removing the server.pid file, if it exists
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      #Change the below values to your own -- Needs to match the values in the db service
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: rails-svelte-network
